added check and error message if the file doesn't exist for getTime

diff --git a/src/wl b/src/wl
--- a/src/wl
+++ b/src/wl
@@ -158,12 +158,17 @@ function getTime {
   colWidth=`stty -a | grep 'columns' | awk -F ';' '{print $3}' | awk '{print $1}'`
   typeset -i curWidth printWidth
   curWidth=$colWidth-43
-  if [[ -e $1 ]]; then
+  if [[ -n $1 ]] && [[ -e $1 ]]; then
     file=$1
   else
     session=$(tmux list-pane -F '#S' | head -1)
     date=$(date +"%y_%m_%d")
     file=~/"work_logs/$session-$date.csv"
+  fi
+
+  if [ ! -f $file ]; then
+    echo "Error: File not found. You can create a new file by running 'wl -n'"
+    exit 2
   fi
 
   row=1
